### ISSUE TITLE
Infer constants over loops

### ISSUE THREAD

**Issue by bechang** [Athithyaa/WalaTest#1]
@Athithyaa, the first challenge with program analysis is handling loops, so I would like to see that you have an implementation that works for simple intra-procedural loops. Please find below an example with 2 asserts that you should be able to prove with constant propagation, but one where you won't able to.

```
class ConstantPropTest {
  void m(int n) {
    int x = 0;
    int y = 0;
    int z = 0;
    int i;
    for (i = 0; i < n; i++) {
      if (i == 3) {
        x = i;
      }
      z = i;
      assert(i == z); // not provable
    }
    y = i;
    assert(x == 3); // provable
  }
}
```

**Comment by Athithyaa** [comment]
Sure. I will work on this. I will keep you updated on the changes I do.

**Comment by bechang** [comment]
Great!

**Comment by Athithyaa** [comment]
The first difficulty I am facing with is examples. Can I get a couple of more examples ? involving for loops ? and what the expected constant propagation would look like ?.

**Comment by bechang** [comment]
Athithyaa, you could probably create many example programs based on the one that I give above. You will want a way to examine the abstract state on the program. The easiest way is probably to print out an annotated program. For testing, it is important and useful to support asserts. You can limit what kind of expression you will support: == and != on variables and constants is all that would be useful with constant propagation.

No need to be fancy. Just something so you can debug and demo your tool to me.

/cc @cernyp

**Comment by Athithyaa** [comment]
I have made some changes to my algorithm. I will go ahead and try to implement some Scala code in my project. 

@bechang I would love to hear some feedback from you.

I used the following loop example to debug my algorithm
~~~~
 public void fun(){
        int z = 3;
        int x = 1;
        int y;
        while (x > 0) {
            if (x == 1)
                y = 7;
            else
                y = z + 4;
            x = 3;
        }
    }
~~~~

**Comment by bechang** [comment]
Great. Go ahead transform my code into a while loop if that helps (although it shouldn't matter since you're working on the WALA IR).
